apiVersion: v1
kind: Service
metadata:
  name: jmartinezl-service
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
